---
- name: Create VM on VMware
  hosts: localhost
  connection: local
  roles:
    - vmware_deploy_vms

- name: Deploy Shinken on vms created by previous play
  hosts: vmware_vms
  roles:
    - deploy_shinken_server
