---
# this piece of code is partially taken from redhat-cop/agnosticd repo
- name: Install required packages
  yum:
     name: "{{ item }}"
     state: latest
  with_items:
    - python
    - python-pip
    - python-devel
    - gcc

- name: Install tower-cli
  pip:
    name: ansible-tower-cli
    state: latest

- name: Configure the tower cli file
  template:
    src: tower-cli.j2
    dest: "~/.tower_cli.cfg"
    mode: 0600

- name: Copy license to tower VM
  copy:
    content: "{{ tower_license }}"
    dest: /root/license.txt

- name: Add the tower license
  command: tower-cli setting modify LICENSE @/root/license.txt --insecure

- name: Remove License file
  file:
    path: /root/license.txt
    state: absent