---
# tasks file for deploy_ansible_tower
- name: Include pre_checks to check if minimum requirements are met
  include_tasks: pre_checks.yml
- block:
  - name: Download Tower Install Tar Ball
    get_url:
      url: "{{ tower_setup_bundle_tar_url }}"
      dest: /tmp/
    register: tower_tar_path
  - debug:
      msg: "Downloaded Tower tar at location {{ tower_tar_path.dest }}"

  - name: Untar Ansible tower setup
    unarchive:
      src: "{{ tower_tar_path.dest }}"
      dest: /tmp/
      remote_src: yes
      extra_opts:
        - --transform
        - s|^[^/]*|setup|

  - name: Remove default password Lines in inventory file
    lineinfile:
      path: "/tmp/setup/inventory"
      line: "{{ item }}"
      state: absent
    loop:
      - admin_password=''
      - pg_password=''
      - rabbitmq_password=''

  - name: add required passwords in inventory file
    lineinfile:
      path: "/tmp/setup/inventory"
      line: "{{ item }}"
    loop:
      - "admin_password='{{ admin_password }}'"
      - "pg_password='{{ pg_password }}'"
      - "rabbitmq_password='{{ rabbitmq_password }}'"

  - name: execute  ./setup.sh script to deploy tower
    shell: ./setup.sh
    args:
      chdir: /tmp/setup


  always:
    - name: remove files/directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ tower_tar_path.dest }}"
        - /tmp/setup